### ISSUE TITLE
removal of go binary package

### ISSUE THREAD

**Issue by sothy** [free5gc/free5gc-stage-2#4]
Do you see any use of go binary package?  My point is to use lib folder without go binary package and use standard go package management to import. what do you think?

**Comment by free5gc-org** [comment]
Hi sothy,
Sorry for late reply.
The lib is remaining to be go:binary-only-file.
There is no plan to open those binaries source code recently.

**Comment by free5gc-org** [comment]
Hi,

The source code of the binary packages is open now.
