### ISSUE TITLE
UPF testGtpv1 is failing

### ISSUE THREAD

**Issue by cidd04** [free5gc/free5gc-stage-2#6]
OS: Ubuntu 18.04
How to reproduce:
1. Follow UPF installation
2. executing sudo ./bin/testgtpv1 will result into the following:

ERRO[2020-03-20T10:08:00Z] c/upf/lib/gtpv1/src/gtp_link.c:32 GtpLinkCreate() GTP device named GtPvLtEsT Create fail  UPF=Util
ERRO[2020-03-20T10:08:00Z] c/upf/lib/gtpv1/test.c:21 testGtpv1_1() GtpLinkCreate ifdev[GtPvLtEsT] fail  UPF=Util

**Comment by free5gc-org** [comment]
Hi,
Please check if kernel GTP module has been installed. You can type the command as below.
```
lsmod | grep gtp
```

If there is no GTP module, please type the command as below to install.
```
sudo modprobe gtp
```

Many Thanks
by free5GC Support Team
